export const HOME_SCREEN = 'lxm.HomeScreen'
export const PLAY_DETAIL_SCREEN = 'lxm.PlayDetailScreen'
export const SONGLIST_DETAIL_SCREEN = 'lxm.SonglistDetailScreen'
export const COMMENT_SCREEN = 'lxm.CommentScreen'
export const VERSION_MODAL = 'lxm.VersionModal'
export const PACT_MODAL = 'lxm.PactModal'
export const SYNC_MODE_MODAL = 'lxm.SyncModeModal'
// export const SETTING_SCREEN = 'lxm.SettingScreen'
// export const TOAST_SCREEN = 'lxm.ToastScreen'

export const HOME_TV_SCREEN = 'lxm.HomeTVScreen'
export const PLAYER_TV_SCREEN = 'lxm.PlayerTVScreen'
export const LIST_DETAIL_TV_SCREEN = 'lxm.ListDetailTVScreen'
export const SEARCH_TV_SCREEN = 'lxm.SearchTVScreen'
export const SETTINGS_TV_SCREEN = 'lxm.SettingsTVScreen'
